### ISSUE TITLE
getHtml 中 Snoopy 获取不到网页内容

### ISSUE THREAD

**Issue by 885783558** [yhf7952/91pornMobile#6]
嘿兄弟，我本地跑起来，getHtml 一直获取不到内容，但是你的演示站还一直都没问题，你觉得是哪里的问题，我还加了  UA、Referer 也没用
function getHtml($url){
    $ip = randIp();
    $snoopy = new Snoopy;

    $snoopy->referer = 'http://www.91porn.com/';
    $snoopy->agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36";

    $snoopy->rawheaders["Accept-language"] = "zh-cn";
    $snoopy->rawheaders["Content-Type"] = "text/html; charset=utf-8";
    $snoopy->rawheaders["CLIENT-IP"] = $ip;
    $snoopy->rawheaders["HTTP_X_FORWARDED_FOR"] = $ip;
    
    $snoopy->fetch($url);
    return $snoopy->results;
}

**Comment by liebesu** [comment]
me too

**Comment by yhf7952** [comment]
是墙的事吗？

**Comment by 885783558** [comment]
额。。是 qiang 的问题，开发环境比较复杂，不好意思
